@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.stasidzie.inkandquill.network.packet;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;