@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.stasidzie.inkandquill.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;